spring.application.name=agri-trade-backend
server.port=8081
server.address=127.0.0.1

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/agritrade
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# No H2 Console for MySQL
spring.h2.console.enabled=false

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
