spring.application.name=agri-trade-backend

# IMPORTANT for Railway
server.port=${PORT:8080}

# REMOVE THIS LINE (don’t bind to localhost)
# server.address=127.0.0.1


# TEMP: Disable DB (for deployment success)
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


# Optional
spring.jpa.show-sql=true
