spring.application.name=agri-trade-backend

server.port=${PORT:8080}

# 🔥 FULLY disable DB (this is the missing piece)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Optional
spring.jpa.show-sql=true
